// Generated by @afokapu/atdd-bun {{VERSION}}. Do not edit; run `atdd-bun integrity init --replace`.
// Fails loudly when the installed package, its generated files, or atdd-bun.yaml were changed.
import { registerIntegrityTest } from "@afokapu/atdd-bun/register";

registerIntegrityTest();
