import { expect, test } from "bun:test";
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { scanDocumentation } from "../src/docs-capability";
import { buildModel, journeyDocs, journeyPaths, nominalPath, renderJourneyDocs } from "../src/journey-docs";
import { loadPlan } from "../src/planner-kernel";

const fixture = resolve(import.meta.dir, "fixtures/journey-docs");
const model = async (root = fixture) => buildModel(await loadPlan(root));

/** A documented repository carrying the fixture plan. */
async function repo() {
  const root = await mkdtemp(join(tmpdir(), "atdd-journeys-"));
  await cp(join(fixture, "plan"), join(root, "plan"), { recursive: true });
  await mkdir(join(root, "docs"), { recursive: true });
  await writeFile(join(root, "docs/index.adoc"), "= Docs\n:doc-id: root\n:status: current\n");
  return root;
}

test("a journey is walked across its interlockings: every path, its end, and the nominal one", async () => {
  const m = await model(), journey = m.journeys[0];
  const paths = journeyPaths(journey, m).map(p => `${p.legs.map(l => `${l.interlocking.split(":")[1]}/${l.route.id}`).join(" > ")} = ${p.end.kind === "terminal" ? p.end.outcome : p.end.kind}`);
  expect(paths).toEqual(["checkout/nominal > payment/charged > fulfilment/ship = shipped", "checkout/nominal > payment/declined = declined", "checkout/empty-cart = rejected"]);
  expect(nominalPath(journey, m)!.legs.map(l => l.route.id)).toEqual(["nominal", "charged", "ship"]);
});

test("what the plan leaves unconnected is reported as gaps, never dropped", async () => {
  expect((await model()).gaps.map(g => `${g.kind}: ${g.subject}`)).toEqual(["unreached interlocking: interlocking:returns", "unrouted train: train:orders:unrouted-refund"]);
  const root = await repo();
  try {
    await rm(join(root, "plan/_journeys"), { recursive: true });
    expect((await model(root)).gaps.filter(g => g.kind === "unreached interlocking").map(g => g.detail)).toEqual(Array(4).fill("the plan declares no journey"));
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("the page and its diagrams are deterministic, complete, and well-formed", async () => {
  const m = await model(), files = renderJourneyDocs(m);
  expect(renderJourneyDocs(await model())).toEqual(files);
  expect([...files.keys()]).toEqual(["index.adoc", "svg/journey-buy.svg", "svg/path-buy-nominal.svg", ...["archive-order", "place-order", "reject-empty-cart", "retry-payment", "ship-order", "take-payment"].map(t => `svg/train-orders-${t}.svg`)]);
  const index = files.get("index.adoc")!;
  for (const text of [":doc-id: purpose.journeys", ":status: generated", "== Buy a product", "=== Nominal path, end to end", "image::svg/journey-buy.svg[Buy a product journey map,opts=inline]", "unreached interlocking", "`+cart.items > 0+`"]) expect(index).toContain(text);
  expect(index).not.toMatch(/\d+\.\d+\.\d+/);
  for (const [file, content] of files) if (file.endsWith(".svg")) {
    expect(content.startsWith("<svg ") && content.trimEnd().endsWith("</svg>"), file).toBeTrue();
    expect(content, file).not.toMatch(/NaN|undefined|Infinity/);
    expect(content.match(/<text /g)?.length, file).toBe(content.match(/<\/text>/g)?.length);
  }
  const walk = files.get("svg/path-buy-nominal.svg")!;
  for (const text of ["Checkout decision → nominal (nominal) → Place an order", "Payment decision → charged (nominal) → Take payment", "outcome: shipped", "var(--atdd-system, #7c3aed)"]) expect(walk).toContain(text);
});

test("the CLI writes, checks, detects a stale view, and never overwrites a hand-written page", async () => {
  const root = await repo();
  const cli = async (...args: string[]) => { const child = Bun.spawn({ cmd: [process.execPath, resolve(import.meta.dir, "../src/cli.ts"), "docs", "journeys", ...args], cwd: root, stdout: "pipe", stderr: "pipe" }); return { code: await child.exited, out: await new Response(child.stdout).text() + await new Response(child.stderr).text() }; };
  try {
    expect((await cli("--check")).code).toBe(1);
    expect((await cli()).out).toContain("wrote 9 file(s)");
    expect((await cli("--check")).code).toBe(0);
    const train = join(root, "plan/_trains/orders/place-order.yaml");
    await writeFile(train, (await readFile(train, "utf8")).replace("Price the cart with current promotions", "Price the cart"));
    const stale = await cli("--check");
    expect(stale.code).toBe(1);
    expect(stale.out).toContain("docs/purpose/journeys/svg/path-buy-nominal.svg, docs/purpose/journeys/svg/train-orders-place-order.svg");
    await writeFile(join(root, "docs/purpose/journeys/index.adoc"), "= Our journeys\n:doc-id: mine\n:status: draft\n");
    expect((await cli()).out).toContain("was not generated by atdd-bun");
    expect(await readFile(join(root, "docs/purpose/journeys/index.adoc"), "utf8")).toContain("Our journeys");
    expect((await cli("--force")).code).toBe(0);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("the docs profile requires a current journey view, and only where it applies", async () => {
  const root = await repo();
  const rule = async () => (await scanDocumentation(root)).filter(v => v.rule_id === "planner.docs.journey-view-current").map(v => v.file);
  try {
    expect(await rule()).toEqual(["docs/purpose/journeys/index.adoc", "docs/purpose/journeys/svg/journey-buy.svg", "docs/purpose/journeys/svg/path-buy-nominal.svg", ...["archive-order", "place-order", "reject-empty-cart", "retry-payment", "ship-order", "take-payment"].map(t => `docs/purpose/journeys/svg/train-orders-${t}.svg`)]);
    await journeyDocs({ root });
    expect(await rule()).toEqual([]);
    await writeFile(join(root, "docs/purpose/journeys/svg/extra.svg"), "<svg/>");
    expect(await rule()).toEqual(["docs/purpose/journeys/svg/extra.svg"]);
    await rm(join(root, "docs"), { recursive: true });
    expect(await rule()).toEqual([]);
  } finally { await rm(root, { recursive: true, force: true }); }
});
