import { readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const version = (await Bun.file(join(root, "package.json")).json() as { version: string }).version;
const render = async (path: string) => (await readFile(join(root, "templates/agents", path), "utf8")).replace("{{VERSION}}", version);
const legacySkillPaths = [".agents/skills/atdd/SKILL.md", ".claude/skills/atdd/SKILL.md"];
// AGENTS.md is read by Codex, Cursor and most agents; CLAUDE.md by Claude Code. Both carry the same block.
export const instructionPaths = ["AGENTS.md", "CLAUDE.md"];
const block = /<!-- atdd-bun:start[\s\S]*?<!-- atdd-bun:end -->\n?/;
const generatedSkill = /<!-- Generated by @afokapu\/atdd-bun /;
/** `current` with the managed block replaced, or appended after at least one blank line; `current` itself is kept. */
const withBlock = (current: string, managed: string) => block.test(current) ? current.replace(block, managed) : `${current}${current ? "\n\n".slice(current.match(/\n{0,2}$/)![0].length) : ""}${managed}`;

/** Write the managed ATDD block in AGENTS.md and CLAUDE.md. Existing files and an existing block are kept unless
 * `replace`; the rest of each instruction file is never touched. Generated legacy skills are retired automatically. */
export async function agentInit(repo = process.cwd(), replace = false) {
  const written: string[] = [], kept: string[] = [], retired: string[] = [];
  for (const path of legacySkillPaths) {
    const output = join(repo, path);
    if (!existsSync(output) || (!replace && !generatedSkill.test(await readFile(output, "utf8")))) continue;
    await rm(output); retired.push(output);
  }
  const managed = await render("AGENTS.block.md");
  for (const path of instructionPaths) {
    const file = join(repo, path), current = existsSync(file) ? await readFile(file, "utf8") : "";
    if (block.test(current) && !replace) { kept.push(file); continue; }
    await writeFile(file, withBlock(current, managed)); written.push(file);
  }
  if (!written.length && !retired.length) return { ok: false, message: `${kept.join(", ")} exist; use --replace` };
  return { ok: true, message: [...written, ...retired.map(path => `${path} removed`)].join("\n") };
}
export async function agentStatus(repo = process.cwd()) {
  const missing: string[] = [];
  for (const path of instructionPaths) { const agents = join(repo, path); if (!existsSync(agents) || !block.test(await readFile(agents, "utf8"))) missing.push(`${agents} (atdd-bun block)`); }
  for (const path of legacySkillPaths) { const skill = join(repo, path); if (existsSync(skill) && generatedSkill.test(await readFile(skill, "utf8"))) missing.push(`${skill} (retired generated skill)`); }
  return { ok: !missing.length, message: missing.length ? `missing: ${missing.join(", ")}` : instructionPaths.map(path => join(repo, path)).join("\n") };
}
