import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
type Release = { enabled?: boolean; version_source?: string; tag_prefix?: string; require_release_intent?: boolean; release_intent_paths?: string[]; publish_sdk?: boolean };
const git = async (root: string, args: string[]) => { const child = Bun.spawn({ cmd: ["git", ...args], cwd: root, stdout: "pipe", stderr: "pipe" }); return { code: await child.exited, out: (await new Response(child.stdout).text()).trim() }; };
const semver = /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;
const cmp = (a: string, b: string) => a.split("-")[0].split(".").map(Number).reduce((r, n, i) => r || Math.sign(n - Number(b.split("-")[0].split(".")[i])), 0);
async function intentFiles(root: string, folders: string[]) { const files: string[] = []; for (const folder of folders.map(path => path.replace("/**", ""))) { const path = join(root, folder); if (!existsSync(path)) continue; for (const entry of await readdir(path, { withFileTypes: true })) if (entry.isFile()) files.push(join(path, entry.name)); } return files; }
export async function releaseCheck(root = process.cwd()) { const config = existsSync(join(root, "atdd-bun.yaml")) ? Bun.YAML.parse(await readFile(join(root, "atdd-bun.yaml"), "utf8")) as { release?: Release } : {}; const policy = config.release; if (!policy?.enabled) return { ok: true, message: "release policy disabled" }; const source = policy.version_source ?? "package.json", pkg = JSON.parse(await readFile(join(root, source), "utf8")) as { version?: string }, version = pkg.version ?? ""; if (!semver.test(version)) return { ok: false, message: `invalid SemVer: ${version}` }; const tags = (await git(root, ["tag", "--merged", "HEAD", "--list", `${policy.tag_prefix ?? "v"}*`])).out.split("\n").filter(Boolean).map(tag => tag.replace(policy.tag_prefix ?? "v", "")).filter(tag => semver.test(tag)); const latest = tags.sort(cmp).at(-1); if (latest && cmp(version, latest) <= 0) return { ok: false, message: `version ${version} is not greater than ${latest}` }; const intents = await intentFiles(root, policy.release_intent_paths ?? [".changeset/**", ".release/**"]); const decisions = (await Promise.all(intents.map(file => readFile(file, "utf8")))).flatMap(text => [...text.matchAll(/\b(patch|minor|major|none)\b/g)].map(match => match[1])); if (policy.require_release_intent && decisions.length !== 1) return { ok: false, message: `exactly one release decision required; found ${decisions.length}` }; if (decisions.some(decision => !["patch", "minor", "major", "none"].includes(decision))) return { ok: false, message: "invalid release decision" }; return { ok: true, message: `release ${decisions[0] ?? "none"}: ${version}` }; }
