import { ciInit, ciStatus } from "./ci";
import { hooksStatus, installHooks } from "./hooks";
import { agentInit, agentStatus } from "./agent";
import { integrityInit, integrityStatus } from "./integrity";
import { concreteProfiles, defaultProfiles, normalizeProfileName } from "./enforce";
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

/** A new atdd-bun.yaml declares every profile explicitly. An absent list runs every profile but governs none, so
 * without this a greenfield repository's first `profiles:` line could switch most of them off unreported. A
 * brownfield repository trims the list before its first commit; after that, dropping one is a reported loosening.
 * An existing explicit profile list gains only its matching generated reject-new policy; all other existing policy
 * remains untouched. */
export async function policyInit(root = process.cwd()) {
  const file = join(root, "atdd-bun.yaml");
  if (existsSync(file)) {
    const text = await readFile(file, "utf8");
    try {
      const config = Bun.YAML.parse(text) as Record<string, unknown>;
      const profiles = config && typeof config === "object" && !Array.isArray(config) && Array.isArray(config.profiles) && config.profiles.length && config.profiles.every(profile => typeof profile === "string") ? config.profiles as string[] : null;
      const normalized = profiles?.map(normalizeProfileName);
      const validProfiles = normalized && normalized.every(profile => concreteProfiles.includes(profile as typeof concreteProfiles[number])) && new Set(normalized).size === normalized.length;
      if (profiles && validProfiles && config.ratchet === undefined) {
        await writeFile(file, `${text.replace(/\s*$/, "")}\nratchet:\n  mode: reject-new\n  profiles: ${JSON.stringify(profiles)}\n`);
        return { ok: true, message: `${file} added ratchet policy` };
      }
    } catch { /* Preserve malformed and non-policy consumer configuration for its normal validation path. */ }
    return { ok: true, message: `${file} kept` };
  }
  await writeFile(file, `# Generated by atdd-bun init. The profiles this repository enforces; trim the list before the first commit to\n# adopt gradually. Once committed, removing a profile or the list is reported by the integrity check.\nprofiles: [${defaultProfiles.join(", ")}]\nratchet:\n  mode: reject-new\n  profiles: [${defaultProfiles.join(", ")}]\n`);
  return { ok: true, message: file };
}

/** Install the package's opt-in local surfaces without touching unrelated
 * workflows or hook paths. Dependency installation itself never calls this. */
export async function initializeRepository(root = process.cwd(), replace = false) {
  // The policy first: the CI workflow and the agent files are rendered from it.
  const policy = await policyInit(root);
  const existingHooks = await hooksStatus(root);
  const hooks = replace || !existingHooks.ok ? await installHooks(root, replace) : existingHooks;
  if (!hooks.ok) return { ok: false, message: `hooks: ${hooks.message}` };

  const existingCi = await ciStatus(root);
  const ci = replace || !existingCi.ok ? await ciInit(root, replace) : existingCi;
  if (!ci.ok) return { ok: false, message: `CI workflow: ${ci.message}` };

  const existingAgent = await agentStatus(root);
  const agent = replace || !existingAgent.ok ? await agentInit(root, replace) : existingAgent;
  if (!agent.ok) return { ok: false, message: `agent instructions: ${agent.message}` };

  const existingIntegrity = await integrityStatus(root);
  const integrity = replace || !existingIntegrity.ok ? await integrityInit(root, replace) : existingIntegrity;
  if (!integrity.ok) return { ok: false, message: `integrity test: ${integrity.message}` };
  return { ok: true, message: `hooks: ${hooks.message}\nCI workflow: ${ci.message}\nagent instructions: ${agent.message}\nintegrity test: ${integrity.message}\npolicy: ${policy.message}` };
}
