import { ciInit, ciStatus } from "./ci";
import { hooksStatus, installHooks } from "./hooks";
import { agentInit, agentStatus } from "./agent";
import { integrityInit, integrityStatus } from "./integrity";
import { concreteProfiles } from "./enforce";
import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

/** A new atdd-bun.yaml declares every profile explicitly. An absent list runs every profile but governs none, so
 * without this a greenfield repository's first `profiles:` line could switch most of them off unreported. A
 * brownfield repository trims the list before its first commit; after that, dropping one is a reported loosening.
 * An existing atdd-bun.yaml is never touched. */
export async function policyInit(root = process.cwd()) {
  const file = join(root, "atdd-bun.yaml");
  if (existsSync(file)) return { ok: true, message: `${file} kept` };
  await writeFile(file, `# Generated by atdd-bun init. The profiles this repository enforces; trim the list before the first commit to\n# adopt gradually. Once committed, removing a profile or the list is reported by the integrity check.\nprofiles: [${concreteProfiles.join(", ")}]\n`);
  return { ok: true, message: file };
}

/** Install the package's opt-in local surfaces without touching unrelated
 * workflows or hook paths. Dependency installation itself never calls this. */
export async function initializeRepository(root = process.cwd(), replace = false) {
  const existingHooks = await hooksStatus(root);
  const hooks = replace || !existingHooks.ok ? await installHooks(root, replace) : existingHooks;
  if (!hooks.ok) return { ok: false, message: `hooks: ${hooks.message}` };

  const existingCi = await ciStatus(root);
  const ci = replace || !existingCi.ok ? await ciInit(root, replace) : existingCi;
  if (!ci.ok) return { ok: false, message: `CI workflow: ${ci.message}` };

  const existingAgent = await agentStatus(root);
  const agent = replace || !existingAgent.ok ? await agentInit(root, replace) : existingAgent;
  if (!agent.ok) return { ok: false, message: `agent skill: ${agent.message}` };

  const existingIntegrity = await integrityStatus(root);
  const integrity = replace || !existingIntegrity.ok ? await integrityInit(root, replace) : existingIntegrity;
  if (!integrity.ok) return { ok: false, message: `integrity test: ${integrity.message}` };
  const policy = await policyInit(root);
  return { ok: true, message: `hooks: ${hooks.message}\nCI workflow: ${ci.message}\nagent skill: ${agent.message}\nintegrity test: ${integrity.message}\npolicy: ${policy.message}` };
}
